# -*- coding: utf-8 -*-
"""Distributed File backup .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQvi3KuNs2SeXe4DDBjcPDS00kUkmI5b
"""

import os
import json
import threading
import pickle
class Coordinator:
    def __init__(self, filename='metadata.json'):
        self.filename = filename
        self.metadata = self.load_metadata()

    def load_metadata(self):
        if os.path.exists(self.filename):

            with open(self.filename, 'r') as file:
                return json.load(file)
        return {}

    def save_metadata(self):
        with open(self.filename, 'w') as file:
            json.dump(self.metadata, file, indent=4)

    def register_file(self, file_name, chunks):
        self.metadata[file_name] = chunks
        self.save_metadata()

    def get_file_chunks(self, file_name):
        return self.metadata.get(file_name, None)

    def display_metadata(self):
        print(json.dumps(self.metadata, indent=4))

class DataNode:
    def __init__(self, node_id, storage_dir='./data'):
        self.node_id = node_id
        self.storage_dir = f'{storage_dir}_{node_id}
        os.makedirs(self.storage_dir, exist_ok=True)

    def store_chunk(self, chunk_name, chunk_data):
        chunk_path = os.path.join(self.storage_dir, chunk_name)
        with open(chunk_path, 'wb') as file:
            file.write(chunk_data)
        print(f"Chunk '{chunk_name}' stored in node {self.node_id}.")

    def get_chunk(self, chunk_name):
        chunk_path = os.path.join(self.storage_dir, chunk_name)
        if os.path.exists(chunk_path):
            with open(chunk_path, 'rb') as file:
                return file.read()
        return None
class MasterNode:
    def __init__(self, data_nodes, coordinator):
        self.data_nodes = data_nodes
        self.coordinator = coordinator

    def distribute_chunks(self, file_name, file_data, replication_factor=2):
        chunk_size = 1024 * 10
        chunk_locations = []
        for i in range(0, len(file_data), chunk_size):
            chunk_data = file_data[i:i + chunk_size]
            chunk_name = f"{file_name}_chunk_{i // chunk_size}"

            primary_node = self.data_nodes[i % len(self.data_nodes)]
            primary_node.store_chunk(chunk_name, chunk_data)
            chunk_locations.append((chunk_name, primary_node.node_id))

            for j in range(1, replication_factor):
                replica_node = self.data_nodes[(i + j) % len(self.data_nodes)]
                replica_node.store_chunk(chunk_name, chunk_data)
                chunk_locations.append((chunk_name, replica_node.node_id))

        self.coordinator.register_file(file_name, chunk_locations)
coordinator = Coordinator()

data_nodes = [DataNode(node_id=i) for i in range(1, 4)]

print("Coordinator and DataNodes initialized.")